version: 2
jobs:
  build:
    docker:
      - image: vvakame/review:5.0
    steps:
      - checkout
      - run:
          name: Setup
          command: npm ci
      - run:
          name: Test
          command: npm test
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "coverimage: cover.png"
          replace: ""
          include: "./articles/config-ebook.yml"
      - run:
          name: Build PDF
          command: npm run pdf
      - store_artifacts:
          path: ./articles/graphql-schema-guide.pdf
          destination: graphql-schema-guide.pdf
